twitter: ""
github: "https://github.com/p5150j"
instagram: ""
linkedin: "https://www.linkedin.com/in/patrickortell/"
dribbble: ""
youtube: ""
facebook: ""
medium: "https://medium.com/@arusio"
patreon: ""
paypal: ""
unsplash: ""
